site_name: Siddhi-Execution-Kalman-Filter
extra_css:
- stylesheets/extra.css
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
pages:
- Welcome to WSO2 Siddhi IO TCP: index.md
- Api:
  - 4.0.2-SNAPSHOT: api/4.0.2-SNAPSHOT.md
- License: license.md
- API Docs:
  - 4.0.2-SNAPSHOT: api/4.0.2-SNAPSHOT.md
theme: material
